import { BusinessProfile, StaffUser, Product, Customer, Expense, DebtRecord, Invoice, CustomRole, StaffPermissions } from '../types';

export const SYSTEM_ROLE_PRESETS: Record<
  string,
  {
    roleId: string;
    title: string;
    description: string;
    badgeColor: string;
    permissions: StaffPermissions;
  }
> = {
  owner: {
    roleId: 'owner',
    title: 'Business Owner / Director',
    description: 'Full unrestricted master access to financial profits, staff administration, settings and database backups.',
    badgeColor: 'bg-emerald-950 text-emerald-300 border-emerald-800',
    permissions: {
      canRecordSales: true,
      canVoidSales: true,
      canDeleteSales: true,
      canApplyDiscounts: true,
      canViewProfit: true,
      canViewCostPrice: true,
      canChangePrices: true,
      canManageInventory: true,
      canDeleteProducts: true,
      canManageExpenses: true,
      canManageDebts: true,
      canManageInvoices: true,
      canViewReports: true,
      canViewFinancialReports: true,
      canExportData: true,
      canManageStaff: true,
      canManageRoles: true,
      canEditSettings: true,
      canManageBackups: true,
      canViewAuditLogs: true,
    },
  },
  manager: {
    roleId: 'manager',
    title: 'Store / Shop Manager',
    description: 'Supervises daily operations, stock management, voids, cashier oversight, and general reports.',
    badgeColor: 'bg-purple-950 text-purple-300 border-purple-800',
    permissions: {
      canRecordSales: true,
      canVoidSales: true,
      canDeleteSales: false, // Protected action (Owner privilege)
      canApplyDiscounts: true,
      canViewProfit: true,
      canViewCostPrice: true,
      canChangePrices: true,
      canManageInventory: true,
      canDeleteProducts: false,
      canManageExpenses: true,
      canManageDebts: true,
      canManageInvoices: true,
      canViewReports: true,
      canViewFinancialReports: true,
      canExportData: true,
      canManageStaff: true,
      canManageRoles: false,
      canEditSettings: false,
      canManageBackups: false,
      canViewAuditLogs: true,
    },
  },
  cashier: {
    roleId: 'cashier',
    title: 'Sales Cashier / Counter',
    description: 'Front-counter sales ring, payment collection, and receipts. Sensitive cost prices and profit margins are locked.',
    badgeColor: 'bg-sky-950 text-sky-300 border-sky-800',
    permissions: {
      canRecordSales: true,
      canVoidSales: false, // Requires supervisor/manager
      canDeleteSales: false, // Forbidden
      canApplyDiscounts: false,
      canViewProfit: false, // RESTRICTED: Hidden from cashier
      canViewCostPrice: false, // RESTRICTED: Hidden from cashier
      canChangePrices: false, // RESTRICTED: Locked
      canManageInventory: false,
      canDeleteProducts: false,
      canManageExpenses: false,
      canManageDebts: true, // Can record customer credit / debt collection at register
      canManageInvoices: false,
      canViewReports: false,
      canViewFinancialReports: false,
      canExportData: false,
      canManageStaff: false,
      canManageRoles: false,
      canEditSettings: false,
      canManageBackups: false,
      canViewAuditLogs: false,
    },
  },
  inventory_manager: {
    roleId: 'inventory_manager',
    title: 'Inventory & Stock Manager',
    description: 'Manages products, incoming supplier restocks, purchase cost updates, and low-stock alerts without sales profit access.',
    badgeColor: 'bg-amber-950 text-amber-300 border-amber-800',
    permissions: {
      canRecordSales: false,
      canVoidSales: false,
      canDeleteSales: false,
      canApplyDiscounts: false,
      canViewProfit: false, // RESTRICTED: Cannot view retail sales margin/profit
      canViewCostPrice: true, // Needs cost price for restock calculation
      canChangePrices: true, // Can update supplier unit costs & catalog selling prices
      canManageInventory: true,
      canDeleteProducts: true,
      canManageExpenses: false,
      canManageDebts: false,
      canManageInvoices: false,
      canViewReports: true, // Inventory stock valuation reports
      canViewFinancialReports: false,
      canExportData: true, // Stock CSV export
      canManageStaff: false,
      canManageRoles: false,
      canEditSettings: false,
      canManageBackups: false,
      canViewAuditLogs: false,
    },
  },
  accountant: {
    roleId: 'accountant',
    title: 'Financial Accountant / Auditor',
    description: 'Financial ledger oversight, operating expenses, receivables/debt recovery, tax/VAT accounting, and P&L reports.',
    badgeColor: 'bg-teal-950 text-teal-300 border-teal-800',
    permissions: {
      canRecordSales: false,
      canVoidSales: false,
      canDeleteSales: false,
      canApplyDiscounts: false,
      canViewProfit: true, // Essential for P&L analysis
      canViewCostPrice: true,
      canChangePrices: false, // Cannot alter live store prices
      canManageInventory: false,
      canDeleteProducts: false,
      canManageExpenses: true,
      canManageDebts: true,
      canManageInvoices: true,
      canViewReports: true,
      canViewFinancialReports: true,
      canExportData: true,
      canManageStaff: false,
      canManageRoles: false,
      canEditSettings: false,
      canManageBackups: false,
      canViewAuditLogs: true,
    },
  },
};

export const INITIAL_CUSTOM_ROLES: CustomRole[] = [
  {
    id: 'role_supervisor',
    businessId: 'biz_001',
    name: 'Shift Supervisor',
    description: 'Senior cashier with permission to void wrong sales and apply approved discount rates.',
    badgeColor: 'bg-indigo-950 text-indigo-300 border-indigo-800',
    permissions: {
      canRecordSales: true,
      canVoidSales: true,
      canDeleteSales: false,
      canApplyDiscounts: true,
      canViewProfit: false,
      canViewCostPrice: false,
      canChangePrices: false,
      canManageInventory: true,
      canDeleteProducts: false,
      canManageExpenses: true,
      canManageDebts: true,
      canManageInvoices: true,
      canViewReports: false,
      canViewFinancialReports: false,
      canExportData: false,
      canManageStaff: false,
      canManageRoles: false,
      canEditSettings: false,
      canManageBackups: false,
      canViewAuditLogs: true,
    },
    createdAt: new Date().toISOString(),
  },
];

export const NIGERIAN_BANKS = [
  'Moniepoint Microfinance Bank',
  'OPay Digital Services',
  'PalmPay',
  'Kuda Microfinance Bank',
  'Guaranty Trust Bank (GTBank)',
  'Zenith Bank',
  'Access Bank',
  'First Bank of Nigeria',
  'United Bank for Africa (UBA)',
  'Stanbic IBTC Bank',
  'FCMB (First City Monument Bank)',
  'Fidelity Bank',
  'Sterling Bank',
  'Wema Bank / ALAT',
  'Union Bank',
  'Providus Bank',
  'Ecobank Nigeria',
  'Jaiz Bank',
  'Taj Bank',
  'Polaris Bank',
  'Keystone Bank',
  'FairMoney MFB',
  'VFD Microfinance Bank',
];

export const NIGERIAN_STATES = [
  'Lagos', 'Abuja (FCT)', 'Rivers (Port Harcourt)', 'Kano', 'Oyo (Ibadan)', 
  'Anambra (Onitsha/Awka)', 'Enugu', 'Delta (Warri/Asaba)', 'Edo (Benin)', 
  'Ogun (Abeokuta)', 'Kaduna', 'Imo (Owerri)', 'Abia (Aba/Umuahia)', 
  'Akwa Ibom (Uyo)', 'Cross River (Calabar)', 'Plateau (Jos)', 'Kwara (Ilorin)', 
  'Osun (Osogbo)', 'Ondo (Akure)', 'Benue', 'Borno', 'Gombe', 'Nasarawa', 'Niger'
];

export const PRODUCT_CATEGORIES = [
  'Provisions & Groceries',
  'Drinks & Beverages',
  'Electronics & Gadgets',
  'Fashion, Fabrics & Shoes',
  'Beauty, Perfumes & Hair',
  'Pharmacy & Toiletries',
  'Food & Restaurant/Chop',
  'Hardware & Building',
  'Automotive & Spares',
  'Services & Repairs',
  'Stationery & Office',
  'General Merchandise',
];

export const EXPENSE_CATEGORIES_CONFIG: Record<string, { label: string; iconEmoji: string; defaultDescription: string }> = {
  generator_fuel: { label: 'Generator Fuel / Petrol', iconEmoji: '⛽', defaultDescription: 'Fuel for shop generator (PMS)' },
  electricity_nepa: { label: 'Electricity / NEPA / Disco Token', iconEmoji: '💡', defaultDescription: 'Prepaid meter electricity recharge' },
  rent: { label: 'Shop Rent & Space', iconEmoji: '🏪', defaultDescription: 'Monthly/Quarterly shop rent contribution' },
  staff_salaries: { label: 'Staff Wages & Daily Allowance', iconEmoji: '👥', defaultDescription: 'Sales girl / boy daily stipend & salary' },
  transport_dispatch: { label: 'Transport & Dispatch Logistics', iconEmoji: '🛵', defaultDescription: 'Market errand fare & dispatch delivery' },
  packaging: { label: 'Nylon Bags & Packaging', iconEmoji: '🛍️', defaultDescription: 'Branded nylon bags & takeaway packs' },
  maintenance: { label: 'Repairs & Generator Servicing', iconEmoji: '🔧', defaultDescription: 'Generator oil change / AC fixing' },
  supplies: { label: 'Shop Supplies & Cleaning', iconEmoji: '🧹', defaultDescription: 'Detergents, receipt paper roll & bulbs' },
  tax_levies: { label: 'Market Dues, LGA & Security Levy', iconEmoji: '📑', defaultDescription: 'Market association & LGA tickets' },
  marketing: { label: 'Adverts & Broadcast Promotion', iconEmoji: '📢', defaultDescription: 'WhatsApp status promos & banners' },
  personal_drawings: { label: 'Owner Withdrawal / Chop Money', iconEmoji: '💼', defaultDescription: 'Owner daily upkeep cash withdrawal' },
  other: { label: 'Miscellaneous / Other', iconEmoji: '📦', defaultDescription: 'General unexpected expenses' },
};

export const INITIAL_BUSINESS_PROFILE: BusinessProfile = {
  id: 'biz_001',
  name: 'Ade & Sons Superstores',
  tagline: 'Quality Provisions & Household Essentials at Wholesales',
  phone: '0803 123 4567',
  email: 'adesuperstores@gmail.com',
  address: 'Shop 14, Trade Fair Complex, Badagry Expressway',
  city: 'Ojo',
  state: 'Lagos',
  cacNumber: 'RC-1849204',
  logoEmoji: '🏬',
  bankAccounts: [
    {
      id: 'bank_1',
      bankName: 'Moniepoint Microfinance Bank',
      accountNumber: '8123456789',
      accountName: 'ADE & SONS SUPERSTORES',
      isDefault: true,
    },
    {
      id: 'bank_2',
      bankName: 'Guaranty Trust Bank (GTBank)',
      accountNumber: '0129384756',
      accountName: 'ADEWALE ISHOLA',
      isDefault: false,
    },
    {
      id: 'bank_3',
      bankName: 'OPay Digital Services',
      accountNumber: '7034567890',
      accountName: 'ADE SUPERSTORES WALLET',
      isDefault: false,
    }
  ],
  currencyCode: 'NGN',
  currencySymbol: '₦',
  showCurrencySymbol: true, // Configurable optional currency display
  taxRate: 0, // No VAT by default for micro retailers
  defaultDiscount: 0,
  lowStockGlobalThreshold: 5,
  receiptFooterMessage: 'Thank you for your patronage! Goods sold in good condition cannot be returned after 48 hours.',
  createdAt: new Date().toISOString(),
};

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'staff_1',
    name: 'Adewale (Owner)',
    role: 'owner',
    pin: '1234',
    avatarColor: 'bg-emerald-600',
    phone: '0803 123 4567',
    isActive: true,
    ...SYSTEM_ROLE_PRESETS.owner.permissions,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'staff_3',
    name: 'Chinedu (Shop Manager)',
    role: 'manager',
    pin: '5678',
    avatarColor: 'bg-purple-600',
    phone: '0902 333 4444',
    isActive: true,
    ...SYSTEM_ROLE_PRESETS.manager.permissions,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'staff_2',
    name: 'Blessing (Cashier)',
    role: 'cashier',
    pin: '0000',
    avatarColor: 'bg-sky-600',
    phone: '0814 987 6543',
    isActive: true,
    ...SYSTEM_ROLE_PRESETS.cashier.permissions,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'staff_4',
    name: 'Emeka (Inventory Manager)',
    role: 'inventory_manager',
    pin: '7788',
    avatarColor: 'bg-amber-600',
    phone: '0802 444 8899',
    isActive: true,
    ...SYSTEM_ROLE_PRESETS.inventory_manager.permissions,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'staff_5',
    name: 'Fatima (Accountant)',
    role: 'accountant',
    pin: '9900',
    avatarColor: 'bg-teal-600',
    phone: '0813 555 1212',
    isActive: true,
    ...SYSTEM_ROLE_PRESETS.accountant.permissions,
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    businessId: 'biz_001',
    name: 'Golden Penny Spaghetti (500g)',
    category: 'Provisions & Groceries',
    sku: 'GPS-500',
    barcode: '615110001020',
    costPrice: 650,
    sellingPrice: 850,
    stockQuantity: 42,
    minStockThreshold: 10,
    unit: 'pcs',
    imageEmoji: '🍝',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    businessId: 'biz_001',
    name: 'Peak Evaporated Milk Tin (150g)',
    category: 'Provisions & Groceries',
    sku: 'PEAK-150',
    barcode: '615110001021',
    costPrice: 520,
    sellingPrice: 700,
    stockQuantity: 18,
    minStockThreshold: 12,
    unit: 'tin',
    imageEmoji: '🥛',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    businessId: 'biz_001',
    name: 'Milo Refill Pack (500g)',
    category: 'Provisions & Groceries',
    sku: 'MILO-500',
    barcode: '615110001022',
    costPrice: 2800,
    sellingPrice: 3400,
    stockQuantity: 8,
    minStockThreshold: 5,
    unit: 'pack',
    imageEmoji: '☕',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    businessId: 'biz_001',
    name: 'Kings Pure Vegetable Oil (5 Litres)',
    category: 'Provisions & Groceries',
    sku: 'KINGS-5L',
    barcode: '615110001023',
    costPrice: 11500,
    sellingPrice: 13500,
    stockQuantity: 3, // Low stock
    minStockThreshold: 5,
    unit: 'keg',
    imageEmoji: '🛢️',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    businessId: 'biz_001',
    name: 'Indomie Onion Chicken Carton (40 x 70g)',
    category: 'Provisions & Groceries',
    sku: 'IND-CTN-40',
    barcode: '615110001024',
    costPrice: 8900,
    sellingPrice: 10200,
    stockQuantity: 14,
    minStockThreshold: 6,
    unit: 'carton',
    imageEmoji: '🍜',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    businessId: 'biz_001',
    name: 'Dangote Refined Sugar (1kg)',
    category: 'Provisions & Groceries',
    sku: 'DNG-SUG-1KG',
    barcode: '615110001025',
    costPrice: 1700,
    sellingPrice: 2100,
    stockQuantity: 2, // Urgent low stock
    minStockThreshold: 6,
    unit: 'pack',
    imageEmoji: '🍚',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_7',
    businessId: 'biz_001',
    name: 'Eva Table Water (75cl x 12 Bottles)',
    category: 'Drinks & Beverages',
    sku: 'EVA-75CL-PK',
    barcode: '615110001026',
    costPrice: 1800,
    sellingPrice: 2400,
    stockQuantity: 25,
    minStockThreshold: 8,
    unit: 'pack',
    imageEmoji: '💧',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_8',
    businessId: 'biz_001',
    name: 'Coca-Cola 50cl Pet Bottle (Crate of 12)',
    category: 'Drinks & Beverages',
    sku: 'COKE-50CL-12',
    barcode: '615110001027',
    costPrice: 3200,
    sellingPrice: 4000,
    stockQuantity: 11,
    minStockThreshold: 5,
    unit: 'pack',
    imageEmoji: '🥤',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_9',
    businessId: 'biz_001',
    name: 'Oraimo Fast Charging Type-C Cable (3A)',
    category: 'Electronics & Gadgets',
    sku: 'ORA-TYPEC-3A',
    barcode: '615110001028',
    costPrice: 1500,
    sellingPrice: 2800,
    stockQuantity: 15,
    minStockThreshold: 4,
    unit: 'pcs',
    imageEmoji: '🔌',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_10',
    businessId: 'biz_001',
    name: 'Dettol Antiseptic Liquid (250ml)',
    category: 'Pharmacy & Toiletries',
    sku: 'DET-250ML',
    barcode: '615110001029',
    costPrice: 1650,
    sellingPrice: 2200,
    stockQuantity: 9,
    minStockThreshold: 4,
    unit: 'bottle',
    imageEmoji: '🧴',
    isActive: true,
    updatedAt: new Date().toISOString(),
  }
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    businessId: 'biz_001',
    name: 'Mama Nkechi (Catering Services)',
    phone: '0802 345 6789',
    email: 'mamankechi@gmail.com',
    address: 'Block B4, Festac Town, Lagos',
    totalPurchases: 284000,
    currentDebt: 35000,
    lastPurchaseDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: 'Regular catering customer. Settles debt bi-weekly after events.',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'cust_2',
    businessId: 'biz_001',
    name: 'Alhaji Musa Bello',
    phone: '0813 999 8877',
    email: 'musa.bello@yahoo.com',
    address: '12 Alaba Road, Ojo, Lagos',
    totalPurchases: 145000,
    currentDebt: 0,
    lastPurchaseDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: 'Always pays via instant bank transfer.',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'cust_3',
    businessId: 'biz_001',
    name: 'Babatunde Adeleke (Barber Shop)',
    phone: '0901 222 3344',
    address: 'Shop 3, Opposite Zenith Bank',
    totalPurchases: 78000,
    currentDebt: 18500,
    lastPurchaseDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    notes: 'Owes for last week provisions. Promised to pay this Friday.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cust_4',
    businessId: 'biz_001',
    name: 'Nurse Chioma (Grace Clinic)',
    phone: '0805 444 1122',
    address: '24 Old Ojo Road, Kuye',
    totalPurchases: 192000,
    currentDebt: 12000,
    lastPurchaseDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    notes: 'Clinic supplies customer.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  }
];

export const SAMPLE_DEBTS: DebtRecord[] = [
  {
    id: 'debt_1',
    businessId: 'biz_001',
    customerId: 'cust_1',
    customerName: 'Mama Nkechi (Catering Services)',
    customerPhone: '0802 345 6789',
    saleId: 'sale_old_1',
    receiptNumber: 'REC-0814',
    initialAmount: 65000,
    balanceDue: 35000,
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    notes: 'Bought 3 cartons of spaghetti and 2 kegs of vegetable oil on credit.',
    status: 'partially_paid',
    history: [
      {
        id: 'dh_1',
        amount: 30000,
        paymentMethod: 'transfer',
        date: new Date(Date.now() - 3 * 86400000).toISOString(),
        receivedByStaff: 'Adewale (Owner)',
        notes: 'Paid ₦30,000 via Moniepoint transfer',
      }
    ],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'debt_2',
    businessId: 'biz_001',
    customerId: 'cust_3',
    customerName: 'Babatunde Adeleke (Barber Shop)',
    customerPhone: '0901 222 3344',
    saleId: 'sale_old_2',
    receiptNumber: 'REC-0820',
    initialAmount: 18500,
    balanceDue: 18500,
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0], // Overdue!
    notes: 'Took Milo, Milk, and indomie carton. Overdue by 2 days.',
    status: 'overdue',
    history: [],
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'debt_3',
    businessId: 'biz_001',
    customerId: 'cust_4',
    customerName: 'Nurse Chioma (Grace Clinic)',
    customerPhone: '0805 444 1122',
    saleId: 'sale_old_3',
    receiptNumber: 'REC-0832',
    initialAmount: 12000,
    balanceDue: 12000,
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    notes: 'Dettol antiseptic and Eva water packs.',
    status: 'active',
    history: [],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  }
];

export const SAMPLE_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    businessId: 'biz_001',
    title: 'Generator Fuel (PMS 15 Litres)',
    category: 'generator_fuel',
    amount: 12750,
    paymentMethod: 'cash',
    date: new Date(Date.now() - 4 * 3600000).toISOString(),
    recordedBy: 'Blessing (Cashier)',
    receiptNote: 'Bought from Total filling station @ ₦850/litre for afternoon light outage',
    isRecurring: true,
    isSynced: true,
  },
  {
    id: 'exp_2',
    businessId: 'biz_001',
    title: 'Nylon Shopping Bags (500 pieces bundle)',
    category: 'packaging',
    amount: 4500,
    paymentMethod: 'transfer',
    date: new Date(Date.now() - 24 * 3600000).toISOString(),
    recordedBy: 'Chinedu (Shop Manager)',
    receiptNote: 'Medium and large branded carriers from Alaba distributor',
    isRecurring: false,
    isSynced: true,
  },
  {
    id: 'exp_3',
    businessId: 'biz_001',
    title: 'Market Taskforce & Security Monthly Levy',
    category: 'tax_levies',
    amount: 3000,
    paymentMethod: 'cash',
    date: new Date(Date.now() - 48 * 3600000).toISOString(),
    recordedBy: 'Adewale (Owner)',
    receiptNote: 'August 2026 security and sanitation clearance ticket',
    isRecurring: true,
    isSynced: true,
  },
  {
    id: 'exp_4',
    businessId: 'biz_001',
    title: 'Shop Assistant Lunch / Daily Feeding Allowance',
    category: 'staff_salaries',
    amount: 2500,
    paymentMethod: 'cash',
    date: new Date(Date.now() - 2 * 3600000).toISOString(),
    recordedBy: 'Adewale (Owner)',
    receiptNote: 'Daily lunch stipend for 2 staff',
    isRecurring: true,
    isSynced: true,
  }
];

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-2026-0042',
    businessId: 'biz_001',
    customerId: 'cust_1',
    customerName: 'Mama Nkechi (Catering Services)',
    customerPhone: '0802 345 6789',
    customerEmail: 'mamankechi@gmail.com',
    customerAddress: 'Block B4, Festac Town, Lagos',
    issueDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    items: [
      { id: 'ii_1', description: 'Kings Pure Vegetable Oil 5L Kegs', quantity: 4, unitPrice: 13500, amount: 54000 },
      { id: 'ii_2', description: 'Indomie Onion Chicken Carton 40pk', quantity: 5, unitPrice: 10200, amount: 51000 },
      { id: 'ii_3', description: 'Golden Penny Spaghetti 500g', quantity: 20, unitPrice: 850, amount: 17000 },
    ],
    subtotal: 122000,
    discountPercent: 2,
    discountAmount: 2440,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 119560,
    amountPaid: 60000,
    balanceDue: 59560,
    status: 'partial',
    bankDetails: {
      bankName: 'Moniepoint Microfinance Bank',
      accountNumber: '8123456789',
      accountName: 'ADE & SONS SUPERSTORES',
    },
    notes: 'Kindly make transfer to our Moniepoint account with invoice number as remark.',
    terms: 'Goods delivered in good condition. Balance payable on or before due date.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  }
];

export const SAMPLE_AUDIT_LOGS = [
  {
    id: 'log_1',
    action: 'Staff Shift Login',
    details: 'Adewale (Owner) authenticated via master PIN at main terminal',
    staffName: 'Adewale (Owner)',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    entityType: 'staff' as const,
  },
  {
    id: 'log_2',
    action: 'Completed POS Sale',
    details: 'Receipt #REC-260820-1088 for ₦14,000 via POS Card terminal',
    staffName: 'Blessing (Cashier)',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    entityType: 'sale' as const,
  },
  {
    id: 'log_3',
    action: 'Recorded Operating Expense',
    details: 'Generator Fuel / Petrol: ₦8,500 (10 Litres PMS fuel for afternoon run)',
    staffName: 'Chinedu (Shop Manager)',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    entityType: 'expense' as const,
  },
  {
    id: 'log_4',
    action: 'Partial Debt Settlement Received',
    details: 'Received ₦10,000 via Bank Transfer from Chief Emeka Okafor for Invoice #REC-260820-1042',
    staffName: 'Blessing (Cashier)',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    entityType: 'debt' as const,
  },
  {
    id: 'log_5',
    action: 'Stock Adjustment & Re-order',
    details: 'Restocked Golden Penny Spaghetti (+50 pcs) at unit cost ₦650',
    staffName: 'Chinedu (Shop Manager)',
    timestamp: new Date(Date.now() - 300 * 60000).toISOString(),
    entityType: 'product' as const,
  },
  {
    id: 'log_6',
    action: 'Updated Financial Settings',
    details: 'Configured default credit grace period to 14 days and cash drawer float to ₦10,000',
    staffName: 'Adewale (Owner)',
    timestamp: new Date(Date.now() - 1440 * 60000).toISOString(),
    entityType: 'financial' as const,
  },
  {
    id: 'log_7',
    action: 'System Snapshot Backup Created',
    details: 'Full JSON database export generated and archived locally',
    staffName: 'Adewale (Owner)',
    timestamp: new Date(Date.now() - 2880 * 60000).toISOString(),
    entityType: 'backup' as const,
  },
];
